version: 2

defaults: &defaults
  working_directory: ~/project/runner
  docker:
    - image: labeldock/circleci-node:8.11

jobs:
  initialize:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: npm module
          command: npm install
      - persist_to_workspace:
          root: ~/project
          paths:
            - runner

  test-basic-fix:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: TEST
          command: npm run basic:fix

  test-vue-fix:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: TEST
          command: npm run vue:fix

workflows:
  version: 2
  task:
    jobs:
      - initialize
      - test-basic-fix:
          requires:
            - initialize
      - test-vue-fix:
          requires:
            - initialize
